[tool.poetry]
name = "temporal_feature_processor"
version = "0.1.0"
description = ""
authors = [
    "Guillermo Etchebarne <getchebarne@tryolabs.com>", 
    "Ian Spektor <ispektor@tryolabs.com>", 
    "Mathieu Guillame-Bert <gbm@google.com>",
    "Richard Stotz <richardstotz@google.com>"
]

[tool.poetry.dependencies]
python = "^3.9"
absl-py = "^1.3.0"
protobuf = "^4.21.12"
pandas = "^1.5.2"
pylint = "^2.15.10"

[tool.poetry.dev-dependencies]
yapf = "^0.32.0"
isort = "^5.11.4"
toml = "^0.10.2"

[tool.yapf]
based_on_style = "google"
indent_width = 2
blank_line_before_module_docstring = true
column_limit = 80

[tool.pylint]
indent-string = '  '
max-line-length = 80

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
